### ISSUE TITLE
Landing Page - Manage Friends

### ISSUE THREAD

**Issue by bjohnson66** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#15]
**As a**
user,

**I want**
the ability to add friends, view and accept friend requests, and manage my friends list,

**So that**
I can build my network, keep track of friend requests, and maintain my connections.

**Comment by halimyu** [comment]
@bjohnson66 should this be on the Friends page instead?

**Comment by bjohnson66** [comment]
ehhh its fine.. i dont want to  make another tag at this point
