### ISSUE TITLE
Game Page - Loading Time

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#33]
As a
user, 
I want
a good experience to have the game ready to play as soon as possible,
So that,
I can start playing without long loading times, with all necessary image resources loaded within 30 seconds.

**Comment by bjohnson66** [comment]
flex

**Comment by RafaelRangelDeLaTejera** [comment]
Consulted with team and I consider that this story is a nice to have but not necessary, I dont know what the plan for making the loading times faster would be
