### ISSUE TITLE
Game Page - Land Type

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#34]
As a 
user,
I want
at least 6 distinct land types, each with unique images,
so that
I can choose the types of stories I want to experience.

**Comment by bjohnson66** [comment]
Instead of this... let GPT hand infinitely many land types?

**Comment by bjohnson66** [comment]
Let GPT get creative basically

**Comment by bjohnson66** [comment]
Add as part of prompt on world generation that GPT generates at least 6 unique tile types

**Comment by bjohnson66** [comment]
We can have GPT generate descriptions fro each tile it, use the API and prompt engineering. But on world start, generate tiles with distinct categories. (eg village, city, barren plain, bog, mountiain region, desert, anceint ruin, farm, fort)
