### ISSUE TITLE
Game Page - Information Display

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#36]
As a
user,
I want
to click the inventory button to see my current items and equipment, (BOTH STORE ITEMS AND GPT ITEMS)
So that
I can track my progress and make informed decisions during gameplay.

**Comment by bjohnson66** [comment]
This story is inventory for game related items (i pick up a torch) as well as purchased items (teleportation or whatever )

**Comment by bjohnson66** [comment]
The in-game items WILL be a comma separted value string FROM GPT.

**Comment by bjohnson66** [comment]
bewcause we hav eNO IDEA what gpt will give us. BTU I will instruct it to be a CSV string for user items.

**Comment by bjohnson66** [comment]
And that way, we can pass it back in to GPT easily as a single string.

**Comment by bjohnson66** [comment]
The store items will be pulled from whatever database Cody decides to use for the shards store

**Comment by bjohnson66** [comment]
This story is NOT about getting GPT to adhere to these rules. its just written to assume that an inventory string exists for all users in the game. and such a string is GAME and character specific.

**Comment by bjohnson66** [comment]
Items that are purchased by a user in the store apply to ALL of their games. it s not game specific.

**Comment by bjohnson66** [comment]
Items will have some kind of description but it is all still CSV
