### ISSUE TITLE
Game Page - Icon Interpretation

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#39]
As a 
user who is not familar with the game,
I want
to know what each icon on the cell means, by simply move my cursor on the icon.
So that
I can know what it represents.

**Comment by bjohnson66** [comment]
Hover over tile:

see string like:

Tile Type: Grassland (this string could jsut be GPT generated) 
Players: <list all if there>

**Comment by RafaelRangelDeLaTejera** [comment]
Consulted with team and I consider that this story is a nice to have but not necessary
