### ISSUE TITLE
Game Page - Smooth GUI

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#41]
As a 
user,
I want
all the elements on the page to change smoothly,
So that
I can easily follow what is happening in the game.

**Comment by bjohnson66** [comment]
It may get done inherently with other stories. I'll keep in backlog anyway

**Comment by RafaelRangelDeLaTejera** [comment]
I don't consider that this is a relevant story given that each GUI element is different and you can't have a story that would change the implementation of all previous stories.

**Comment by RafaelRangelDeLaTejera** [comment]
see previous comment
