### ISSUE TITLE
Game Page - Quest Showing

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#43]
As a 
user,
I want
to check my current quest progress on the page,
So that
I can know how I did in the past.

**Comment by bjohnson66** [comment]
This will be similar to the inventory. th equests are all GPT basesed and will be stored  in a string like:

(Quest description, completion status), (Save princess , done), (go to bathroom, not done)..... as a single string

**Comment by bjohnson66** [comment]
Not story quests but achievement type ones
