### ISSUE TITLE
Game Page - Activity Log

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#44]
As a
user,
I want
to check the activity log of myself or other players,
So that
I can see how each player has behaved in the past.

**Comment by bjohnson66** [comment]
duplicate of [#52](https://github.com/uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007/issues/52)

**Comment by RafaelRangelDeLaTejera** [comment]
I dont consider this is a relevant story, if you implement the chat it is basically this. Adding this to the game would add too much stuff and might overwhelm the user. Most games dont have a log and I also dont see where this would go on the game page
