### ISSUE TITLE
Game Page - Results Screen

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#46]
As a 
user,
I want
to see a result screen with user stats on it, and rewards earned,
so that,
I can know how I performed in the game.

**Comment by bjohnson66** [comment]
I dont think there is a game over so this may not apply

**Comment by RafaelRangelDeLaTejera** [comment]
From what the team has told me the current game play does not end and it doesn not have a clear winner. The game is more of an open world story that the users play and can keep playing. I dont see what the stats page would include. Given the short amount of time left for sprint 3 I will close this issue
