### ISSUE TITLE
Game Page - Event Story Match

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#49]
**As a** 

player,

**I want** 

the event story to align with my character's stats,

**So that**

I feel fully immersed in my role.

**Comment by RafaelRangelDeLaTejera** [comment]
I think this is not a testable issue because the story gets generated by GPT so you should put this issue as a comment on the issue where you implement the logic of asking GPT for the user story so that you include in your prompt that the story has to consider the players stats
