### ISSUE TITLE
Game Page - Teammate Icons

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#51]
**As I **

player,

**I want**

to see the other players icons next to their names,

**so that**

I know their username.

**Comment by bjohnson66** [comment]
make profile pics show up in gaem page

**Comment by RafaelRangelDeLaTejera** [comment]
Consulted with team and I consider that this story is a nice to have but not necessary
