### ISSUE TITLE
Game Page - Answer GPT Box

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#56]
**As a**

player,

**I want**

to receive a description of what is happening in the session and respond to GPT,

**so that**

I can be immersed in the role-palying experience of the game.

**Comment by bjohnson66** [comment]
(single player) do this before other one

**Comment by bjohnson66** [comment]
Using API gem from:
https://github.com/alexrudall/ruby-openai?tab=readme-ov-file
