### ISSUE TITLE
Game Page - Event Choices

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#57]
**As a** 

player,

**I want**

choices that lead to different event outcomes,

**So that**

I can feel responsible for my own decisions.

**Comment by bjohnson66** [comment]
inherent to prompt

**Comment by RafaelRangelDeLaTejera** [comment]
Does not apply to the GPT gameplay that was described to the customer
