### ISSUE TITLE
Game Page - Event Affect

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#59]
**As a**

player,

**I want**

encounter a unique story that can give my character a buff or debuff,

**So that** 

I can take risks to boost my abilities.

**Comment by bjohnson66** [comment]
inherent to GPT

**Comment by RafaelRangelDeLaTejera** [comment]
This story is related to how the prompts get formatted so you can maybe add this story as a comment to the story that implements the prompt for GPT
