### ISSUE TITLE
Game Page - Deaths

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#60]
**As a** 

player whose character has died,

**I want** 

the ability to spend shards to resurrect my character,

**So that**

I can continue playing without losing my progress or starting over.

**Comment by bjohnson66** [comment]
I do need to handle deaths with system prompt actual behavior is wishy washy

**Comment by bjohnson66** [comment]
part of sys prompt closing
