### ISSUE TITLE
Game Page - Game Over

### ISSUE THREAD

**Issue by zhasa18** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#62]
**As a** 

player,

**I want**

to win when I achieve the goals, and the game should over

**so that** 

everyone can go to the result page and claim thier rewards.

**Comment by bjohnson66** [comment]
does not apply

**Comment by RafaelRangelDeLaTejera** [comment]
Since the game is an open world map and does not end this does not apply
